// File generated by FlutterFire configuration for Gym Chuột
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static const String firestoreDatabaseId =
      'ai-studio-remixitp-75e20961-0a5c-4216-bd36-e7cb2845de7b';

  static const String oAuthClientId =
      '36141190693-d0m46n8esl9cv37b2l6tr45e09h8blh6.apps.googleusercontent.com';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlpcLDohZYWG-UnpXORXUUd9O5xE53QL8',
    appId: '1:36141190693:web:296e4573992876765939cc',
    messagingSenderId: '36141190693',
    projectId: 'project-8129dcb9-c383-42e8-b10',
    authDomain: 'project-8129dcb9-c383-42e8-b10.firebaseapp.com',
    storageBucket: 'project-8129dcb9-c383-42e8-b10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlpcLDohZYWG-UnpXORXUUd9O5xE53QL8',
    appId: '1:36141190693:web:296e4573992876765939cc',
    messagingSenderId: '36141190693',
    projectId: 'project-8129dcb9-c383-42e8-b10',
    storageBucket: 'project-8129dcb9-c383-42e8-b10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlpcLDohZYWG-UnpXORXUUd9O5xE53QL8',
    appId: '1:36141190693:web:296e4573992876765939cc',
    messagingSenderId: '36141190693',
    projectId: 'project-8129dcb9-c383-42e8-b10',
    storageBucket: 'project-8129dcb9-c383-42e8-b10.firebasestorage.app',
    iosBundleId: 'com.gymchuot.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlpcLDohZYWG-UnpXORXUUd9O5xE53QL8',
    appId: '1:36141190693:web:296e4573992876765939cc',
    messagingSenderId: '36141190693',
    projectId: 'project-8129dcb9-c383-42e8-b10',
    storageBucket: 'project-8129dcb9-c383-42e8-b10.firebasestorage.app',
    iosBundleId: 'com.gymchuot.app',
  );
}
